[theme]
# Primary accent color for interactive elements.
primaryColor = "#F39C12"

# Background color for the main content area.
backgroundColor = "#ECF0F1"

# Background color used for the sidebar and most interactive widgets.
secondaryBackgroundColor = "#BDC3C7"

# Color used for almost all text.
textColor = "#2C3E50"

# Font family for all text in the app, except code blocks. One of "sans serif", "serif", or "monospace".
# Default: "sans serif"
font = "sans serif"
